"""empty message

Revision ID: b764fcc03287
Revises: 7ff87af47547
Create Date: 2024-01-08 16:45:22.226474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b764fcc03287'
down_revision = '7ff87af47547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rotation', sa.Integer(), nullable=False))
        batch_op.drop_column('region')
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('rotation')
        batch_op.drop_column('diameter')

    # ### end Alembic commands ###
